import "./globals.css";
import { MedievalSharp } from "next/font/google";

// Components
import Navbar from "./components/Navbar";

const medievalSharp = MedievalSharp({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={medievalSharp.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
